In [1]:
import numpy as np
import numpy.linalg as lin

In [2]:
a = np.array([[1,1],[2,1]])
print(a)
print(a.shape)

a_ = lin.inv(a) #역행열
print(a_)

y = np.array([2,4])
print(y.shape)   # (2,) <-벡터

y = np.array([2,4]).reshape(2,1)
print(y.shape) # (2, 1) <-행렬

[[1 1]
 [2 1]]
(2, 2)
[[-1.  1.]
 [ 2. -1.]]
(2,)
(2, 1)


In [3]:
w=a_ * y #단순한 산술 곱. 차원이 안맞아도 곱해지는 이유 : 브로드캐스팅 기능때문.
print(w)

[[-2.  2.]
 [ 8. -4.]]


In [4]:
w = np.matmul(a_,y)
print(w)
print(w.shape)

[[2.]
 [0.]]
(2, 1)


In [5]:
# 정방행렬(nxn)이 아닐경우, 역행렬 구하는 법.
a = np.array([[1,1],[2,1],[3,1]])
print(a)
print(a.shape)

a_ = lin.pinv(a)
print(a_)
print(a_.shape)

y=np.array([2, 4, 6.4]).reshape(3,1)
w=np.matmul(a_,y)
print(w)

[[1 1]
 [2 1]
 [3 1]]
(3, 2)
[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]
(2, 3)
[[ 2.2       ]
 [-0.26666667]]


In [6]:
print(1*w[0][0]+w[1][0])
# 행렬 a에서 x=1일때 y=1이었지만, 결과는 1.933이 나옴.
# w는 선형회귀이기 때문.

x_ = np.array([[-1,1],[0,1],[1,1],[2,1]])
np.matmul(x_,w)

1.9333333333333322


array([[-2.46666667],
       [-0.26666667],
       [ 1.93333333],
       [ 4.13333333]])